// Audio 2B — generates src/game/audioWarmBanks.generated.js.
//
// Derives, per deferred runtime group, the exact audio URLs that group's
// scripts reference (from the asset audit's reference map). The tiered loader
// prefetches these the moment the group loads, so lazily-constructed
// HTMLAudioElements and runtime fetch()+decodeAudioData paths start from the
// HTTP cache instead of a trigger-time network round-trip.
//
// The Arsenal AV HOT bank (referenced by arsenalPresentationRuntime.js) is
// EXCLUDED: those clips are fetched + decoded into AudioBuffers by the AV
// runtime's own preload (AudioBuffer authority), and double-fetching them as
// media elements would race the cache for no benefit.
//
// Usage: node tools/assetAudit.mjs && node tools/generateAudioWarmBanks.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { MODE_DEFERRED_RUNTIMES } from '../src/game/runtimeManifest.js';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AUDIT = path.join(REPO, 'reports', 'asset-audit.json');
const OUT = path.join(REPO, 'src', 'game', 'audioWarmBanks.generated.js');

const AUDIO_EXTS = new Set(['.mp3', '.ogg', '.wav', '.m4a', '.aac', '.flac']);
const AV_RUNTIME = 'public/game/arsenal/arsenalPresentationRuntime.js';

const audit = JSON.parse(fs.readFileSync(AUDIT, 'utf8'));
const avAudio = new Set(
  audit.assets
    .filter((a) => AUDIO_EXTS.has(path.extname(a.path)) && a.shipRefs.some((r) => r.file === AV_RUNTIME))
    .map((a) => a.path),
);

const banks = {};
for (const [group, entries] of Object.entries(MODE_DEFERRED_RUNTIMES)) {
  const scripts = new Set(entries.map((e) => 'public' + String(e[0]).split('?')[0]));
  const urls = new Set();
  for (const asset of audit.assets) {
    if (!AUDIO_EXTS.has(path.extname(asset.path))) continue;
    if (asset.classification !== 'SHIPPING_LAZY' && asset.classification !== 'SHIPPING_HOT') continue;
    if (avAudio.has(asset.path)) continue;
    if (asset.shipRefs.some((r) => scripts.has(r.file))) urls.add(asset.path);
  }
  if (urls.size) banks[group] = [...urls].sort();
}

const banner = `// AUTO-GENERATED by tools/generateAudioWarmBanks.mjs — audio warm banks for
// the tiered runtime loader (Audio 2B). Regenerate after changing runtime
// audio references: node tools/assetAudit.mjs && node tools/generateAudioWarmBanks.mjs
// Excludes the Arsenal AV HOT bank (AudioBuffer-decoded by its own preload).
export const AUDIO_WARM_BANKS = ${JSON.stringify(banks, null, 2)};
`;

fs.writeFileSync(OUT, banner);
const total = Object.values(banks).reduce((s, l) => s + l.length, 0);
console.log(`wrote ${path.relative(REPO, OUT)}: ${Object.keys(banks).length} groups, ${total} urls (${avAudio.size} AV HOT-bank urls excluded)`);
