import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
const source=path.resolve('tools/testArsenalBattleHeadless.mjs');
const temp=path.resolve('tools/.rivet-boss-fixture-'+randomUUID()+'.mjs');
try{
  fs.writeFileSync(temp,fs.readFileSync(source,'utf8')+"\nif(process.argv.includes('--b7d-genuine-standalone')){\n const v=run(\"window.__APEX_TEST_MODE=true;\\nconst started=window.__apexQuestRivetBossFixtureStart?.()===true;\\nconst A=window.APEX_ARSENAL,W=A?.weaponApi,actors=window.fighters||[];\\nif(!started||!A?.state?.questRivetBossTest||actors.length!==2)\\n  return {started,active:A?.state?.questRivetBossTest};\\nconst hero=actors[0],boss=actors[1],authority=A.state.questRivetBossAuthority;\\nconst checkpoint=window.APEX_QUEST01_DIRECTOR?.checkpoint?.()?.checkpointId??null;\\nA.state.spawnHeld=true;A.state.spawnTimer=1000000;A.state.slots=[];\\nfor(const f of actors){f.baseSpeed=0;f.data.__hrHoldBody=true;}\\nhero.x=160;hero.y=500;boss.x=640;boss.y=500;\\nlet fired=0,physicalHits=0;\\nwhile(boss.hp>180&&fired++<80){\\n  const before=boss.hp;\\n  W.fireBullet({owner:hero,x:250,y:500,angle:0,speed:2800,\\n    damage:100,weapon:'PISTOL'});\\n  for(let i=0;i<12;i++)A.step(.025);\\n  if(boss.hp<before)physicalHits++;\\n}\\nconst snap=authority.snapshot();\\nconst final={hp:boss.hp,max:boss.maxHp,visual:boss.questVisualId,\\n  heroHp:hero.hp,team:boss.questTeam,\\n  thresholds:snap.cues.map(x=>x.threshold),stopped:snap.stopped,\\n  outcome:A.state.questOutcome,over:A.state.over,\\n  damageDone:hero.damageDone,damageTaken:boss.damageTaken};\\nfor(let i=0;i<4;i++)boss.takeDamage(1000,hero,'post-stop-real-damage');\\nconst after={hp:boss.hp,cues:authority.snapshot().cues.length};\\nconst checkpointAfter=window.APEX_QUEST01_DIRECTOR?.checkpoint?.()?.checkpointId??null;\\nwindow.exitArsenalBattleMode();\\nconst closed=authority.snapshot().closed===true&&A.state.questRivetBossAuthority==null;\\nwindow.__APEX_TEST_MODE=false;\\nconst blocked=window.__apexQuestRivetBossFixtureStart?.()===false;\\nreturn {started,checkpoint,checkpointAfter,final,after,fired,physicalHits,closed,blocked};\");\n gate('B7d authentic new hostile Iron Bulwark RIVET',v?.started===true&&v.final?.team==='HOSTILE'&&v.final.visual==='bulwark'&&v.final.max===1000,v?.final);\n gate('B7d native projectiles cross 750 450 180 without killing RIVET',v?.physicalHits>0&&v.final.hp===180&&v.final.thresholds.join('|')==='750|450|180'&&v.final.stopped===true,{hits:v?.physicalHits,final:v?.final});\n gate('B7d correct genuine damage and fixture-only finish',v?.final?.damageDone>0&&v.final.damageTaken>0&&v.final.heroHp>0&&v.final.outcome==='COMPLETE'&&v.final.over==='QUEST_RIVET_BOSS_TEST_COMPLETE',v?.final);\n gate('B7d further real Fighter hits cannot cause damage or duplicate cues',v?.after?.hp===180&&v.after.cues===3,v?.after);\n gate('B7d no synthetic story checkpoint',v?.checkpoint===v?.checkpointAfter&&v?.checkpointAfter!=='RIVET_OVERRIDDEN',v?.checkpointAfter);\n gate('B7d battle exits cleanly and rejects non-test mode',v?.closed===true&&v?.blocked===true,{closed:v?.closed,blocked:v?.blocked});\n}\n");
  const p=spawnSync(process.execPath,[temp,'--product-authentic','--b7d-genuine-standalone'],{
    cwd:process.cwd(),encoding:'utf8',maxBuffer:8*1024*1024,stdio:'inherit'
  });
  if(p.error)throw p.error;
  if(p.status!==0)process.exitCode=p.status||1;
}finally{fs.rmSync(temp,{force:true});}
