#!/usr/bin/env node
/* MIRROR V1 — CHECKPOINT D1 raster-parity gate.
 *
 * The product law forbids simplifying Gold into generic VFX, and the usual way
 * that happens is a hand-port that "looks close". This gate does not look at
 * anything: it bakes the atlas in BOTH the canonical Gold page and the shipped
 * production module and requires the resulting bitmaps to be BYTE-IDENTICAL.
 *
 * Any drift at all — a changed stop colour, a dropped facet, a different bake
 * order perturbing the seeded br() stream — moves a sha256 and fails here.
 */
import { createRequire } from 'node:module';
import fs from 'node:fs';
import crypto from 'node:crypto';

const require = createRequire('/tmp/magnet-browser-deps/x.js');
const puppeteer = require('puppeteer-core');
const chromiumModule = require('@sparticuz/chromium');
const chromium = chromiumModule.default || chromiumModule;
process.env.LD_LIBRARY_PATH = ['/tmp/al2023', '/tmp/al2023/lib', process.env.LD_LIBRARY_PATH].filter(Boolean).join(':');

const BASE = process.env.APEX_GOLD_URL || 'http://127.0.0.1:4200';
const GOLD_REL = 'docs/hero-rework/mirror-v1/gold/MIRROR_GOLD_FUSION_12.html';
const GOLD_URL = `${BASE}/${GOLD_REL}`;
const MOD_URL = `${BASE}/public/game/hero-rework/mirrorGoldV1.js`;
const EXPECT_SHA = 'c11a8f0fba8e3c37f1180e7746a9169a443be1a1c51d95fbdc464c3c50ef5205';

const report = { gates: {}, failures: [] };
function gate(name, ok, detail) {
  report.gates[name] = { pass: !!ok, detail };
  if (!ok) report.failures.push(name);
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail === undefined ? '' : `  — ${typeof detail === 'string' ? detail : JSON.stringify(detail)}`}`);
}

const bytes = fs.readFileSync(GOLD_REL);
const sha = crypto.createHash('sha256').update(bytes).digest('hex');
gate('D1-00-gold-unmodified', sha === EXPECT_SHA, { sha });
if (sha !== EXPECT_SHA) process.exit(1);

// The shipped module must be a bridge artifact, not a hand edit.
const modSrc = fs.readFileSync('public/game/hero-rework/mirrorGoldV1.js', 'utf8');
gate('D1-01-module-is-generated-and-cites-gold',
  modSrc.includes('GENERATED by tools/bridgeMirrorGoldV1.mjs')
  && modSrc.includes(EXPECT_SHA) && modSrc.includes('DO NOT EDIT BY HAND'), null);
const modCodeEarly = modSrc.split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
gate('D1-02-module-owns-no-gameplay-clock',
  !/requestAnimationFrame|setTimeout|setInterval/.test(modCodeEarly)
  // castA1/castA2/stepA1/stepA2 are D3's AUTHORED presentation timeline entry
  // points. They report canonical edges and perform no gameplay, which is
  // asserted separately by D3-05/D3-06. What must stay absent is a clock.
  && !/function (resetAll|buildAuto|autoStep)\s*\(/.test(modCodeEarly), null);
// Strip line comments before scanning, so the header's own explanation of why
// Math.random is absent cannot be mistaken for a use of it.
const modCode = modSrc.split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
// D1 had no rr() at all. D2 legitimately uses rr(), but it must resolve to the
// instance's DEDICATED mulberry32 stream, never to Math.random, so that
// presentation can never consume the gameplay/combat RNG.
gate('D1-03-module-has-no-ambient-rng',
  !/Math\.random/.test(modCode)
  && /const rr = \(a, b\) => a \+ __rand\(\) \* \(b - a\);/.test(modCode)
  && /let __rand = mulberry32\(/.test(modCode),
  { mathRandomHits: (modCode.match(/Math\.random/g) || []).length,
    rrBoundToDedicatedStream: /a \+ __rand\(\)/.test(modCode) });

const browser = await puppeteer.launch({
  executablePath: await chromium.executablePath(),
  args: [...chromium.args.filter((a) => !/use-gl|use-angle|swiftshader|gpu/.test(a)), '--disable-gpu'],
  headless: true,
  protocolTimeout: 900000,
});

let goldAtlas, prodAtlas, prodMeta, pageErrors = [];
try {
  // ---- canonical Gold atlas ----
  const gp = await browser.newPage();
  gp.on('pageerror', (e) => pageErrors.push('gold: ' + e));
  await gp.goto(GOLD_URL, { waitUntil: 'load', timeout: 120000 });
  await gp.waitForFunction(() => typeof P === 'object' && P.Lh && P.Lh.lv, { timeout: 60000 });
  goldAtlas = await gp.evaluate(() => {
    const out = {};
    for (const k of Object.keys(P)) {
      const p = P[k];
      out[k] = { w: p.w, h: p.h, ox: p.ox, oy: p.oy, levels: p.lv.map((l) => ({ s: l.s, url: l.c.toDataURL('image/png') })) };
    }
    return out;
  });

  // ---- production module atlas, baked in a bare page ----
  const pp = await browser.newPage();
  pp.on('pageerror', (e) => pageErrors.push('prod: ' + e));
  await pp.goto(`${BASE}/`, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await pp.addScriptTag({ url: MOD_URL });
  await pp.waitForFunction(() => window.apexMirrorGoldV1 === 'ready', { timeout: 60000 });
  const res = await pp.evaluate(() => {
    const G = window.APEX_MIRROR_GOLD;
    const ok = G.ensureBaked();
    const out = {};
    if (ok) {
      for (const k of Object.keys(G.P)) {
        const p = G.P[k];
        out[k] = { w: p.w, h: p.h, ox: p.ox, oy: p.oy, levels: p.lv.map((l) => ({ s: l.s, url: l.c.toDataURL('image/png') })) };
      }
    }
    // ---- D2 probe: per-instance state, dedicated RNG, history, locomotion ----
    let d2 = { ok: false, err: null };
    try {
      const realRandom = Math.random;
      let mathRandomCalls = 0;
      Math.random = function () { mathRandomCalls++; return realRandom(); };

      const A = G.createMirrorInstance({ seed: 1 });
      const B = G.createMirrorInstance({ seed: 1 });
      const C = G.createMirrorInstance({ seed: 2 });
      const sa = [A.random(), A.random(), A.random()];
      const sb = [B.random(), B.random(), B.random()];
      const sc = [C.random(), C.random(), C.random()];
      const rngRepeatable = sa.every((v, i) => v === sb[i]);
      const rngDiffersBySeed = sa.some((v, i) => v !== sc[i]);

      A.M.x = 400; A.M.y = 400; A.histFill();
      B.M.x = 700; B.M.y = 700; B.histFill();
      const independent = A.M.x !== B.M.x && A.hist !== B.hist;

      const inst = G.createMirrorInstance({ seed: 7 });
      inst.M.x = 100; inst.M.y = 100; inst.histFill();
      inst.M.x = 500; inst.M.y = 100;
      for (let i = 0; i < 12; i++) inst.pushHist();
      const histNow = inst.hs(0, 0);
      const histPast = inst.hs(inst.constants.STEP * 30, 0);
      const historyLag = Math.abs(histNow - histPast) > 1;

      const L = G.createMirrorInstance({ seed: 3 });
      L.M.x = 500; L.M.y = 500; L.histFill();
      const STEP = L.constants.STEP;
      L.onStart(1, 0);
      const startMv = L.M.mv;
      for (let i = 0; i < 60; i++) { L.M.drive = { x: 1, y: 0 }; L.stepMirror(STEP); }
      const sustainedMv = L.M.mv, sustainedX = L.M.x;
      L.onStop(L.M.vx, L.M.vy);
      // mv decays over real time; 10 steps at 1/120 is only 0.083s.
      for (let i = 0; i < 90; i++) { L.M.drive = null; L.stepMirror(STEP); }
      const stoppedMv = L.M.mv;
      const stoppedVel = Math.hypot(L.M.vx, L.M.vy);
      const locomotion = { startMv: +startMv.toFixed(4), sustainedMv: +sustainedMv.toFixed(4),
        stoppedMv: +stoppedMv.toFixed(4), stoppedVel: +stoppedVel.toFixed(2),
        movedX: +(sustainedX - 500).toFixed(1) };
      const locomotionDistinct = sustainedX > 500 && startMv < sustainedMv && stoppedVel < 1;

      const Tn = G.createMirrorInstance({ seed: 4 });
      Tn.M.x = 500; Tn.M.y = 500; Tn.histFill();
      for (let i = 0; i < 30; i++) { Tn.M.drive = { x: 1, y: 0 }; Tn.stepMirror(STEP); }
      // onTurn's authored reaction: it kicks the half whose side matches the
      // NEW heading (nx>=0 ? R : L) on x/y, sets E.G, and stamps the four
      // false-face plates with escalating extraDelays.
      const beforeTurn = Tn.H.L.x.v;
      Tn.onTurn(1, 0, -1, 0);
      const afterTurn = Tn.H.L.x.v;
      const turnExtraDelays = Tn.PL.map((x) => x.extraDelay);
      for (let i = 0; i < 10; i++) { Tn.M.drive = { x: -1, y: 0 }; Tn.stepMirror(STEP); }
      const hardTurn = afterTurn !== beforeTurn
        && JSON.stringify(turnExtraDelays) === JSON.stringify([0.035, 0.055, 0.08, 0.12]);

      const P2 = G.createMirrorInstance({ seed: 5 });
      const plateDelays = P2.PL.map((p) => ({ id: p.id, role: p.role, dl: p.dl }));
      P2.wrongPlate(P2.PL[3], 0.5);
      const wrongExtraDelay = P2.PL[3].extraDelay;

      // ---- D3: A1/A2 authored choreography ----
      const X = G.createMirrorInstance({ seed: 11 });
      X.M.x = 400; X.M.y = 500; X.F.x = 700; X.F.y = 500; X.histFill();
      const STEP3 = X.constants.STEP;
      let ownEdge = null;
      X.on('ownEdge', (e) => { if (!ownEdge) ownEdge = e; });
      X.castA1(false);
      const busyA1 = X.M.busy;
      let t = 0, endA1 = null;
      for (let i = 0; i < 400; i++) { X.stepA1(STEP3); t += STEP3; if (!X.A1.on && endA1 === null) { endA1 = t; break; } }
      // whiff must not reach the OWN edge grant
      const Xw = G.createMirrorInstance({ seed: 12 });
      Xw.M.x = 400; Xw.M.y = 500; Xw.F.x = 700; Xw.F.y = 500; Xw.histFill();
      let whiffOwn = null; Xw.on('ownEdge', (e) => { whiffOwn = e; });
      Xw.castA1(true);
      for (let i = 0; i < 400 && Xw.A1.on; i++) Xw.stepA1(STEP3);
      const whiffCopy = Xw.M.copyOn;

      // A2: snap at the canonical first fixed-step crossing, no actor move
      const Y = G.createMirrorInstance({ seed: 13 });
      Y.M.x = 400; Y.M.y = 500; Y.F.x = 700; Y.F.y = 500; Y.histFill();
      const beforeM = { x: Y.M.x, y: Y.M.y }, beforeF = { x: Y.F.x, y: Y.F.y };
      Y.castA2();
      const busyA2 = Y.M.busy;
      let t2 = 0, snapT = null;
      for (let i = 0; i < 400; i++) {
        Y.stepA2(STEP3); t2 += STEP3;
        if (snapT === null && Y.A2.res > 0) snapT = t2;
        if (!Y.A2.on && t2 > 0.1) break;
      }
      const movedByPresentation = Y.M.x !== beforeM.x || Y.F.x !== beforeF.x;
      // with applyExchange the same code DOES move its own presentation actors
      const Z = G.createMirrorInstance({ seed: 13, applyExchange: true });
      Z.M.x = 400; Z.M.y = 500; Z.F.x = 700; Z.F.y = 500; Z.histFill();
      Z.castA2();
      for (let i = 0; i < 60; i++) Z.stepA2(STEP3);
      const exchangeApplied = Z.M.x === 700 && Z.F.x === 400;

      Math.random = realRandom;
      const d3 = { ok: true, busyA1, ownEdgeT: ownEdge ? +ownEdge.t.toFixed(5) : null,
        ownEdgeU: ownEdge ? +ownEdge.u.toFixed(4) : null, endA1: endA1 === null ? null : +endA1.toFixed(5),
        whiffReachedOwn: whiffOwn !== null, whiffCopy,
        busyA2, snapT: snapT === null ? null : +snapT.toFixed(5),
        movedByPresentation, exchangeApplied,
        removedMutations: G.d3RemovedMutations ? G.d3RemovedMutations.length : 0 };

      d2 = { ok: true, d3, err: null, HN: A.HN, HS: A.HS, histLength: A.hist.length,
        independent, aRoot: A.M.x, bRoot: B.M.x,
        rngRepeatable, rngDiffersBySeed, rngSample: sa.map((v) => +v.toFixed(6)),
        mathRandomCalls, historyLag, histNow: +histNow.toFixed(2), histPast: +histPast.toFixed(2),
        locomotion, locomotionDistinct, hardTurn,
        turnInfo: { beforeHalfVx: +beforeTurn.toFixed(2), afterHalfVx: +afterTurn.toFixed(2),
          plateExtraDelays: turnExtraDelays },
        plateDelays, wrongExtraDelay };
      d2.d3 = d3;
    } catch (e) { d2 = { ok: false, err: String((e && e.stack) || e) }; }

    return { ok, err: G.bakeError ? String(G.bakeError) : null, atlas: out,
      version: G.version, checkpoint: G.checkpoint, names: G.ASSET_NAMES, ref: G.GOLD_REF, d2 };
  });
  prodAtlas = res.atlas; prodMeta = res;
  gate('D1-04-production-module-bakes', res.ok === true, res.err);
} finally {
  await browser.close();
}

const digest = (atlas) => {
  const o = {};
  for (const k of Object.keys(atlas).sort()) {
    const a = atlas[k];
    o[k] = {
      box: `${a.w}x${a.h}@${a.ox},${a.oy}`,
      levels: a.levels.map((l) => `${l.s}:${crypto.createHash('sha256').update(l.url).digest('hex').slice(0, 16)}`),
    };
  }
  return o;
};
const gd = digest(goldAtlas);
const pd = digest(prodAtlas || {});

const goldNames = Object.keys(gd);
const prodNames = Object.keys(pd);
gate('D1-05-same-asset-inventory',
  goldNames.length > 0 && goldNames.length === prodNames.length && goldNames.every((n) => prodNames.includes(n)),
  { gold: goldNames.length, prod: prodNames.length,
    missing: goldNames.filter((n) => !prodNames.includes(n)),
    extra: prodNames.filter((n) => !goldNames.includes(n)) });

const boxDiffs = goldNames.filter((n) => pd[n] && gd[n].box !== pd[n].box);
gate('D1-06-identical-asset-geometry', boxDiffs.length === 0,
  boxDiffs.map((n) => ({ asset: n, gold: gd[n].box, prod: pd[n].box })));

const pxDiffs = goldNames.filter((n) => !pd[n] || JSON.stringify(gd[n].levels) !== JSON.stringify(pd[n].levels));
gate('D1-07-BYTE-IDENTICAL-raster-no-drift', pxDiffs.length === 0,
  pxDiffs.length ? pxDiffs.map((n) => ({ asset: n, gold: gd[n].levels, prod: pd[n].levels })) : `${goldNames.length} assets bit-exact`);

// The named inventory from Gold's own diagnostic sheet must all be present.
const SHEET = ['Lh', 'Rh', 'UL', 'UR', 'LL', 'LR', 'shard', 'eshard', 'ghost', 'eL', 'eR', 'sL', 'sR'];
gate('D1-08-canonical-asset-sheet-complete', SHEET.every((n) => pd[n]),
  SHEET.filter((n) => !pd[n]));
gate('D1-09-split-face-and-plates-present',
  !!(pd.Lh && pd.Rh && pd.UL && pd.UR && pd.LL && pd.LR), null);
gate('D1-10-shard-and-node-assets-present', !!(pd.shard && pd.eshard),
  { nv: prodMeta && prodMeta.ref ? prodMeta.ref.NV : null });
gate('D1-11-gold-ref-exported',
  !!(prodMeta && prodMeta.ref && prodMeta.ref.MIRROR_R === 34 && prodMeta.ref.ARENA === 1000
     && prodMeta.ref.REF_SPACE === 1254 && Array.isArray(prodMeta.ref.NV) && prodMeta.ref.NV.length === 5),
  prodMeta && prodMeta.ref);
/* ---------------- CHECKPOINT D2: temporal history + locomotion ---------------- */
const d2 = prodMeta && prodMeta.d2;
gate('D2-01-per-instance-factory-exists', !!(d2 && d2.ok), d2 && d2.err);
gate('D2-02-history-ring-is-HN64-HS22',
  !!d2 && d2.HN === 64 && d2.HS === 22 && d2.histLength === 64 * 22,
  d2 && { HN: d2.HN, HS: d2.HS, histLength: d2.histLength });
gate('D2-03-instances-are-independent', !!d2 && d2.independent === true,
  d2 && { aRoot: d2.aRoot, bRoot: d2.bRoot });
gate('D2-04-dedicated-rng-deterministic-and-seeded',
  !!d2 && d2.rngRepeatable === true && d2.rngDiffersBySeed === true,
  d2 && { repeatable: d2.rngRepeatable, differsBySeed: d2.rngDiffersBySeed, sample: d2.rngSample });
gate('D2-05-presentation-never-consumes-math-random',
  !!d2 && d2.mathRandomCalls === 0, d2 && { calls: d2.mathRandomCalls });
gate('D2-06-history-samples-the-past-not-the-present',
  !!d2 && d2.historyLag === true, d2 && { now: d2.histNow, past: d2.histPast });
gate('D2-07-locomotion-start-sustained-stop-distinct',
  !!d2 && d2.locomotionDistinct === true, d2 && d2.locomotion);
gate('D2-08-hard-turn-registers', !!d2 && d2.hardTurn === true, d2 && d2.turnInfo);
gate('D2-09-false-face-plates-have-distinct-role-delays',
  !!d2 && Array.isArray(d2.plateDelays) && d2.plateDelays.length === 4
  && new Set(d2.plateDelays.map((x) => x.dl)).size === 4, d2 && d2.plateDelays);
gate('D2-10-wrong-plate-adds-authored-extra-delay',
  !!d2 && d2.wrongExtraDelay === 0.04, d2 && { extraDelay: d2.wrongExtraDelay });

/* ---------------- CHECKPOINT D3: A1 / A2 authored choreography ---------------- */
const d3 = d2 && d2.d3;
gate('D3-01-a1-a2-timeline-ported', !!(d3 && d3.ok), d3);
gate('D3-02-a1-OWN-edge-at-canonical-first-crossing',
  !!d3 && Math.abs(d3.ownEdgeT - 0.93333) < 0.009 && d3.ownEdgeU >= 0.58,
  d3 && { t: d3.ownEdgeT, u: d3.ownEdgeU, canonical: 0.93333 });
gate('D3-03-a1-visual-end-canonical',
  !!d3 && Math.abs(d3.endA1 - 1.475) < 0.02, d3 && { endA1: d3.endA1, canonical: 1.475 });
gate('D3-04-a1-busy-envelope-2p2', !!d3 && d3.busyA1 === 2.2, d3 && { busy: d3.busyA1 });
gate('D3-05-whiff-never-reaches-OWN-grant',
  !!d3 && d3.whiffReachedOwn === false && d3.whiffCopy !== true,
  d3 && { reachedOwn: d3.whiffReachedOwn, copyOn: d3.whiffCopy });
gate('D3-06-a2-snap-at-canonical-first-crossing',
  !!d3 && Math.abs(d3.snapT - 0.25833) < 0.009, d3 && { snapT: d3.snapT, canonical: 0.25833 });
gate('D3-07-a2-busy-envelope-1p8', !!d3 && d3.busyA2 === 1.8, d3 && { busy: d3.busyA2 });
gate('D3-08-presentation-does-not-relocate-actors',
  !!d3 && d3.movedByPresentation === false,
  d3 && { movedByPresentation: d3.movedByPresentation });
gate('D3-09-exchange-applies-only-when-gameplay-supplies-it',
  !!d3 && d3.exchangeApplied === true, d3 && { exchangeApplied: d3.exchangeApplied });
gate('D3-10-demo-gameplay-mutations-enumerated-and-removed',
  !!d3 && d3.removedMutations === 4, d3 && { removed: d3.removedMutations });

gate('D1-99-no-page-errors', pageErrors.length === 0, pageErrors);

fs.mkdirSync('docs/hero-rework/mirror-v1/evidence', { recursive: true });
fs.writeFileSync('docs/hero-rework/mirror-v1/evidence/d1-raster-parity.json', JSON.stringify({
  generatedAt: new Date().toISOString(),
  purpose: 'Checkpoint D1: the shipped Gold static/material core bakes a BYTE-IDENTICAL atlas to canonical Gold.',
  gold: { path: GOLD_REL, sha256: sha },
  module: { path: 'public/game/hero-rework/mirrorGoldV1.js', version: prodMeta && prodMeta.version },
  assetCount: goldNames.length,
  d2: prodMeta && prodMeta.d2, d3: prodMeta && prodMeta.d2 && prodMeta.d2.d3,
  goldDigest: gd, productionDigest: pd,
  ...report, pass: report.failures.length === 0,
}, null, 2));

const total = Object.keys(report.gates).length;
console.log(`\n[MIRROR D1 RASTER PARITY] ${total - report.failures.length}/${total} gates passed`);
if (report.failures.length) console.log(`FAILURES: ${report.failures.join(', ')}`);
process.exit(report.failures.length ? 1 : 0);
