import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const w={};w.window=w;
vm.runInNewContext(readFileSync('public/game/quest/questCompanionKitCandidate.js','utf8'),w);
const K=w.APEX_QUEST_COMPANION_KIT_CANDIDATE;
const equal=(a,b,msg)=>{assert.equal(a,b,msg);console.log('PASS '+msg);};
const actor=(id,team,x,y,hp=1000)=>({questId:id,questTeam:team,x,y,hp,maxHp:1000,withdrawn:false,dir:{x:1,y:0}});
const n=actor('NEWBOT','ALLY',100,100,510);
const t=actor('T.O.T','ALLY',180,120);
const v=actor('RIVET','ALLY',320,120,350);
const e1=actor('BREACH-A1','HOSTILE',395,120,300);
const e2=actor('BREACH-A2','HOSTILE',399,175,300);
const e3=actor('BREACH-A3','HOSTILE',290,480,300);
let all=[n,t,v,e1,e2,e3];
const invoke=(owner,slot,actors=all,encounterId='E06')=>K.plan({owner,slot,actors,encounterId});
equal(K.shippingGameplay,false,'candidate never claims to be playable');
equal(K.requiresOwnerApproval,true,'owner has final say on canon');
equal(invoke(t,'J').ok,true,'T.O.T J selects real nearby hostiles');
equal(invoke(t,'J').targetQuestIds.length,2,'J caps at two genuine hostile bodies');
equal(invoke(t,'J').targetQuestIds[0],'BREACH-A1','stable nearest-first targeting');
equal(invoke(t,'K').targetQuestIds[0],'NEWBOT','guard selects weakest living ally');
n.withdrawn=true;
equal(invoke(t,'K').targetQuestIds[0],'RIVET','guard hands off after real withdrawal');
v.withdrawn=true;
equal(invoke(t,'K').targetQuestIds[0],'T.O.T','solo fallback does not invent ally');
v.withdrawn=false;n.withdrawn=false;
equal(invoke(v,'J').targetQuestIds[0],'BREACH-A1','RIVET holds one nearest real enemy');
equal(invoke(v,'K').ok,true,'RIVET K uses current native heading and cone');
equal(invoke(v,'K').targetQuestIds.includes('BREACH-A3'),false,'cone cannot hit behind/outside range');
equal(invoke(v,'K').targetQuestIds.length,2,'cone affects only in-front real targets');
v.dir={x:-1,y:0};
equal(invoke(v,'K').ok,false,'no omnidirectional or free invisible hit');
v.dir={x:1,y:0};
t.withdrawn=true;
equal(invoke(t,'J').ok,false,'withdrawn T.O.T cannot cast');
t.withdrawn=false;
equal(invoke(t,'J',all,'E07').ok,false,'E07/E08 cannot inherit E06 companion skills');
const pre=JSON.stringify(all);
const res=invoke(v,'K');
equal(res.impactRequiresNativeRecheck,true,'windup requires real impact-time recheck');
equal(JSON.stringify(all),pre,'planning is pure: no HP, geometry, status, or weapon mutations');
equal(K.C['T.O.T'].K.selfDamageMultiplier>0,true,'T.O.T is never invulnerable');
equal(K.C.RIVET.J.damage,0,'RIVET clamp never fabricates damage');
equal(K.C.RIVET.K.nativeImpactDamage,45,'RIVET strike specified for real takeDamage only');
console.log('B6m candidate preflight contract: 19 checks');
