#!/usr/bin/env node
/* MIRROR V1 — CHECKPOINT D1 raster-parity gate.
 *
 * The product law forbids simplifying Gold into generic VFX, and the usual way
 * that happens is a hand-port that "looks close". This gate does not look at
 * anything: it bakes the atlas in BOTH the canonical Gold page and the shipped
 * production module and requires the resulting bitmaps to be BYTE-IDENTICAL.
 *
 * Any drift at all — a changed stop colour, a dropped facet, a different bake
 * order perturbing the seeded br() stream — moves a sha256 and fails here.
 */
import { createRequire } from 'node:module';
import fs from 'node:fs';
import crypto from 'node:crypto';

const require = createRequire('/tmp/magnet-browser-deps/x.js');
const puppeteer = require('puppeteer-core');
const chromiumModule = require('@sparticuz/chromium');
const chromium = chromiumModule.default || chromiumModule;
process.env.LD_LIBRARY_PATH = ['/tmp/al2023', '/tmp/al2023/lib', process.env.LD_LIBRARY_PATH].filter(Boolean).join(':');

const BASE = process.env.APEX_GOLD_URL || 'http://127.0.0.1:4200';
const GOLD_REL = 'docs/hero-rework/mirror-v1/gold/MIRROR_GOLD_FUSION_12.html';
const GOLD_URL = `${BASE}/${GOLD_REL}`;
const MOD_URL = `${BASE}/public/game/hero-rework/mirrorGoldV1.js`;
const EXPECT_SHA = 'c11a8f0fba8e3c37f1180e7746a9169a443be1a1c51d95fbdc464c3c50ef5205';

const report = { gates: {}, failures: [] };
function gate(name, ok, detail) {
  report.gates[name] = { pass: !!ok, detail };
  if (!ok) report.failures.push(name);
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail === undefined ? '' : `  — ${typeof detail === 'string' ? detail : JSON.stringify(detail)}`}`);
}

const bytes = fs.readFileSync(GOLD_REL);
const sha = crypto.createHash('sha256').update(bytes).digest('hex');
gate('D1-00-gold-unmodified', sha === EXPECT_SHA, { sha });
if (sha !== EXPECT_SHA) process.exit(1);

// The shipped module must be a bridge artifact, not a hand edit.
const modSrc = fs.readFileSync('public/game/hero-rework/mirrorGoldV1.js', 'utf8');
gate('D1-01-module-is-generated-and-cites-gold',
  modSrc.includes('GENERATED by tools/bridgeMirrorGoldV1.mjs')
  && modSrc.includes(EXPECT_SHA) && modSrc.includes('DO NOT EDIT BY HAND'), null);
const modCodeEarly = modSrc.split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
gate('D1-02-module-owns-no-gameplay-clock',
  !/requestAnimationFrame|setTimeout|setInterval/.test(modCodeEarly)
  && !/function (step|resetAll|castA1|castA2)\s*\(/.test(modCodeEarly), null);
// Strip line comments before scanning, so the header's own explanation of why
// Math.random is absent cannot be mistaken for a use of it.
const modCode = modSrc.split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
gate('D1-03-module-has-no-ambient-rng',
  !/Math\.random/.test(modCode) && !/(^|[^\w])rr\(/m.test(modCode),
  { mathRandomHits: (modCode.match(/Math\.random/g) || []).length });

const browser = await puppeteer.launch({
  executablePath: await chromium.executablePath(),
  args: [...chromium.args.filter((a) => !/use-gl|use-angle|swiftshader|gpu/.test(a)), '--disable-gpu'],
  headless: true,
  protocolTimeout: 900000,
});

let goldAtlas, prodAtlas, prodMeta, pageErrors = [];
try {
  // ---- canonical Gold atlas ----
  const gp = await browser.newPage();
  gp.on('pageerror', (e) => pageErrors.push('gold: ' + e));
  await gp.goto(GOLD_URL, { waitUntil: 'load', timeout: 120000 });
  await gp.waitForFunction(() => typeof P === 'object' && P.Lh && P.Lh.lv, { timeout: 60000 });
  goldAtlas = await gp.evaluate(() => {
    const out = {};
    for (const k of Object.keys(P)) {
      const p = P[k];
      out[k] = { w: p.w, h: p.h, ox: p.ox, oy: p.oy, levels: p.lv.map((l) => ({ s: l.s, url: l.c.toDataURL('image/png') })) };
    }
    return out;
  });

  // ---- production module atlas, baked in a bare page ----
  const pp = await browser.newPage();
  pp.on('pageerror', (e) => pageErrors.push('prod: ' + e));
  await pp.goto(`${BASE}/`, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await pp.addScriptTag({ url: MOD_URL });
  await pp.waitForFunction(() => window.apexMirrorGoldV1 === 'ready', { timeout: 60000 });
  const res = await pp.evaluate(() => {
    const G = window.APEX_MIRROR_GOLD;
    const ok = G.ensureBaked();
    const out = {};
    if (ok) {
      for (const k of Object.keys(G.P)) {
        const p = G.P[k];
        out[k] = { w: p.w, h: p.h, ox: p.ox, oy: p.oy, levels: p.lv.map((l) => ({ s: l.s, url: l.c.toDataURL('image/png') })) };
      }
    }
    return { ok, err: G.bakeError ? String(G.bakeError) : null, atlas: out,
      version: G.version, checkpoint: G.checkpoint, names: G.ASSET_NAMES, ref: G.GOLD_REF };
  });
  prodAtlas = res.atlas; prodMeta = res;
  gate('D1-04-production-module-bakes', res.ok === true, res.err);
} finally {
  await browser.close();
}

const digest = (atlas) => {
  const o = {};
  for (const k of Object.keys(atlas).sort()) {
    const a = atlas[k];
    o[k] = {
      box: `${a.w}x${a.h}@${a.ox},${a.oy}`,
      levels: a.levels.map((l) => `${l.s}:${crypto.createHash('sha256').update(l.url).digest('hex').slice(0, 16)}`),
    };
  }
  return o;
};
const gd = digest(goldAtlas);
const pd = digest(prodAtlas || {});

const goldNames = Object.keys(gd);
const prodNames = Object.keys(pd);
gate('D1-05-same-asset-inventory',
  goldNames.length > 0 && goldNames.length === prodNames.length && goldNames.every((n) => prodNames.includes(n)),
  { gold: goldNames.length, prod: prodNames.length,
    missing: goldNames.filter((n) => !prodNames.includes(n)),
    extra: prodNames.filter((n) => !goldNames.includes(n)) });

const boxDiffs = goldNames.filter((n) => pd[n] && gd[n].box !== pd[n].box);
gate('D1-06-identical-asset-geometry', boxDiffs.length === 0,
  boxDiffs.map((n) => ({ asset: n, gold: gd[n].box, prod: pd[n].box })));

const pxDiffs = goldNames.filter((n) => !pd[n] || JSON.stringify(gd[n].levels) !== JSON.stringify(pd[n].levels));
gate('D1-07-BYTE-IDENTICAL-raster-no-drift', pxDiffs.length === 0,
  pxDiffs.length ? pxDiffs.map((n) => ({ asset: n, gold: gd[n].levels, prod: pd[n].levels })) : `${goldNames.length} assets bit-exact`);

// The named inventory from Gold's own diagnostic sheet must all be present.
const SHEET = ['Lh', 'Rh', 'UL', 'UR', 'LL', 'LR', 'shard', 'eshard', 'ghost', 'eL', 'eR', 'sL', 'sR'];
gate('D1-08-canonical-asset-sheet-complete', SHEET.every((n) => pd[n]),
  SHEET.filter((n) => !pd[n]));
gate('D1-09-split-face-and-plates-present',
  !!(pd.Lh && pd.Rh && pd.UL && pd.UR && pd.LL && pd.LR), null);
gate('D1-10-shard-and-node-assets-present', !!(pd.shard && pd.eshard),
  { nv: prodMeta && prodMeta.ref ? prodMeta.ref.NV : null });
gate('D1-11-gold-ref-exported',
  !!(prodMeta && prodMeta.ref && prodMeta.ref.MIRROR_R === 34 && prodMeta.ref.ARENA === 1000
     && prodMeta.ref.REF_SPACE === 1254 && Array.isArray(prodMeta.ref.NV) && prodMeta.ref.NV.length === 5),
  prodMeta && prodMeta.ref);
gate('D1-99-no-page-errors', pageErrors.length === 0, pageErrors);

fs.mkdirSync('docs/hero-rework/mirror-v1/evidence', { recursive: true });
fs.writeFileSync('docs/hero-rework/mirror-v1/evidence/d1-raster-parity.json', JSON.stringify({
  generatedAt: new Date().toISOString(),
  purpose: 'Checkpoint D1: the shipped Gold static/material core bakes a BYTE-IDENTICAL atlas to canonical Gold.',
  gold: { path: GOLD_REL, sha256: sha },
  module: { path: 'public/game/hero-rework/mirrorGoldV1.js', version: prodMeta && prodMeta.version },
  assetCount: goldNames.length,
  goldDigest: gd, productionDigest: pd,
  ...report, pass: report.failures.length === 0,
}, null, 2));

const total = Object.keys(report.gates).length;
console.log(`\n[MIRROR D1 RASTER PARITY] ${total - report.failures.length}/${total} gates passed`);
if (report.failures.length) console.log(`FAILURES: ${report.failures.join(', ')}`);
process.exit(report.failures.length ? 1 : 0);
